### ISSUE TITLE
handle i15r messages in partials

### ISSUE THREAD

**Issue by balinterdi** [balinterdi/i15r#1]
Currently it generates something like this:

```
en:
  tickets:
    _book_info:
      book_info: BOOK INFO
```

Probably just removing the underscore is ok.
